const clgData = [
    "XLRI Xavier School of Management",
    "Institute of Rural Management",
    "Banaras Hindu University",
    "Indian Institute of Foreign Trade, Delhi",
    "Symbiosis Institute of Business Management",
    "SRM UNIVERSITY",
    "IISER",
    "Nit Durgapur",
    "Dr D Y Patil",
    "Indian Institute of Technology (IIT) Bhubaneshwar",
    "Indian Institute of Technology (IIT) Madras, Chennai",
    "Indian Institute of Technology (IIT) Guwahati",
    "Indian Institute of Technology (IIT) Indore",
    "Indian Institute of Technology (IIT) Kanpur",
    "Indian Institute of Technology (IIT) Kharagpur",
    "Indian Institute of Technology (IIT) Hyderabad",
    "Indian Institute of Technology (IIT) Bombay, Mumbai",
    "Indian Institute of Technology (IIT) New Delhi",
    "Indian Institute of Technology (IIT) Mandi",
    "Indian Institute of Technology (IIT) Roorkee",
    "Indian Institute of Technology (Banaras Hindu University) Varanasi",
    "Indian Institute of Technology (IIT) Bhilai",
    "Indian Institute of Technology (Indian School of Mines) Dhanbad",
    "National Institute of Technology, Warangal, Telangana",
    "National Institute of Technology, Silchar, Assam",
    "National Institute of Technology, Calicut, Kerala",
    "National Institute of Technology, Delhi",
    "National Institute of Technology, Goa",
        "Indian Institute of Technology Madras",
        "Indian Institute of Science, Bengaluru",
        "Indian Institute of Technology Bombay",
        "Indian Institute of Technology Delhi",
        "Indian Institute of Technology Kanpur",
        "Indian Institute of Technology Kharagpur",
        "All India Institute of Medical Sciences Delhi",
        "Indian Institute of Technology Roorkee",
        "Indian Institute of Technology Guwahati",
        "Jawaharlal Nehru University",
        "Banaras Hindu University",
        "Indian Institute of Technology Hyderabad",
        "Jamia Millia Islamia",
        "Manipal Academy of Higher Education, Manipal",
        "University of Delhi",
        "Aligarh Muslim University",
        "Jadavpur University",
        "Amrita Vishwa Vidyapeetham",
        "Vellore Institute of Technology",
        "Anna University",
        "S.R.M. Institute of Science and Technology",
        "Saveetha Institute of Medical and Technical Sciences",
        "Birla Institute of Technology and Science, Pilani",
        "Siksha 'O' Anusandhan",
        "University of Hyderabad",
        "Calcutta University",
        "Homi Bhabha National Institute",
        "Kalinga Institute of Industrial Technology",
        "Indian Institute of Technology Gandhinagar",
        "Indian Institute of Technology (Banaras Hindu University)",
        "National Institute of Technology Tiruchirappalli",
        "Chandigarh University",
        "Indian Institute of Technology Indore",
        "National Institute of Technology Rourkela",
        "Indian Institute of Technology (Indian School of Mines) Dhanbad",
        "JSS Academy of Higher Education and Research",
            "Savitribai Phule Pune University",
            "Kerala University",
            "Jawaharlal Institute of Post Graduate Medical Education and Research",
            "Koneru Lakshmaiah Education Foundation University",
            "Andhra University, Visakhapatnam",
            "Indian Institute of Science Education and Research Pune",
            "Thapar Institute of Engineering and Technology (Deemed-to-be-university)",
            "Bharathiar University",
            "Lovely Professional University",
            "National Institute of Technology Karnataka, Surathkal",
            "Shanmugha Arts Science Technology and Research Academy",
            "Indian Institute of Technology Ropar",
            "Amity University Gautam Budh Nagar",
            "Kalasalingam Academy of Research and Education",
            "Cochin University of Science and Technology",
            "Symbiosis International",
            "National Institute of Technology Warangal",
            "National Institute of Technology Calicut",
            "Bharathidasan University",
            "Institute of Chemical Technology",
            "Gauhati University",
            "Babasaheb Bhimrao Ambedkar University",
            "UPES",
            "Panjab University Chandigarh",
            "Indian Institute of Science Education and Research Kolkata",
            "Jamia Hamdard",
            "Dr. D. Y. Patil Vidyapeeth",
            "University of Madras",
            "Indian Institute of Science Education and Research Mohali",
            "Delhi Technological University",
            "Mahatma Gandhi University, Kottayam",
            "Indian Institute of Technology Jodhpur",
            "University of Kashmir",
            "Osmania University",
            "Datta Meghe Institute of Higher Education and Research",
            "Indian Institute of Technology Mandi",
            "Indian Institute of Technology Patna",
            
                "All India Institute of Medical Sciences Rishikesh",
                "Indian Statistical Institute, Kolkata",
                "Alagappa University",
                "Visvesvaraya National Institute of Technology Nagpur",
                "Indian Institute of Science Education and Research Bhopal",
                "Graphic Era University",
                "Punjab Agricultural University",
                "Sri Sivasubramaniya Nadar College of Engineering",
                "Malaviya National Institute of Technology Jaipur",
                "All India Institute of Medical Sciences Jodhpur",
                "SVKM's Narsee Monjee Institute of Management Studies",
                "Sathyabama Institute of Science and Technology",
                "Mysore University",
                "University of Jammu",
                "King George's Medical University",
                "Shoolini University of Biotechnology and Management Sciences",
                "Christ University",
                "Bharath Institute of Higher Education and Research",
                "National Institute of Technology Silchar",
                "National Institute of Technology Durgapur",
                "Gujarat University",
                "Shiv Nadar University",
                "Sri Ramachandra Institute of Higher Education and Research",
                "Acharya Nagarjuna University",
                "Tata Institute of Social Sciences",
                "All India Institute of Medical Sciences Patna",
                "Periyar University",
                "other"    
            
  ];
  
  const clgOptions = clgData.map(clg => ({
    label: clg,
    value: clg
  }));
   
export default clgOptions  